namespace EliteFS.Migrations
{
    using EliteFS.EliteModels;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<EliteFS.Models.EliteDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "EliteFS.Models.EliteDbContext";
        }

        protected override void Seed(EliteFS.Models.EliteDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //You can use the DbSet<T>.AddOrUpdate() helper extension method
            //to avoid creating duplicate seed data.

            var categories = new List<Category>
            {
                new Category{ CategoryName = "Hat" },
                new Category{ CategoryName = "Dress" },
                new Category{ CategoryName = "Wallet" },
                new Category{ CategoryName = "Clothes" },
                new Category{ CategoryName = "Wallet" },
                new Category{ CategoryName = "Bag" },
                new Category{ CategoryName = "Sunglasses" },
                new Category{ CategoryName = "Swimwear" }
             };
            foreach (var item in categories)
            {
                context.Categories.Add(item);
            }
            context.SaveChanges();

            var roles = new List<Role>
            {
                    new Role{ RoleName = "Administrator" },
                    new Role{ RoleName = "Mod" },
                    new Role{ RoleName = "User" },
                    new Role{ RoleName = "Guest" },
                    new Role{ RoleName = "Customer" },
             };
            foreach (var item in roles)
            {
                context.Roles.Add(item);
            }
            context.SaveChanges();

            var users = new List<User> {
                    new User { Username = "Armand", Password = "1", FirstName = "Dora", LastName = "Stephen", Address = "Ap #577-8162 Pellentesque, Ave", PhoneNumber = "1-866-144-5090", Email = "ultricies.sem.magna@dolor.net", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Amos", Password = "1", FirstName = "Caesar", LastName = "Hayes", Address = "488-9932 Sed Rd.", PhoneNumber = "1-218-312-7516", Email = "iaculis.enim.sit@ultricesVivamusrhoncus.edu", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Victor", Password = "1", FirstName = "Hunter", LastName = "Simon", Address = "9296 Velit St.", PhoneNumber = "1-985-164-3678", Email = "Sed.dictum@erat.org", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Cedric", Password = "1", FirstName = "Catherine", LastName = "Rajah", Address = "Ap #425-6983 Dignissim St.", PhoneNumber = "1-702-900-6906", Email = "nunc.sed@Mauris.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Abel", Password = "1", FirstName = "Jackson", LastName = "Reese", Address = "125-4954 Donec Rd.", PhoneNumber = "1-974-274-9427", Email = "mauris.sagittis@augue.edu", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Kennedy", Password = "1", FirstName = "Brynne", LastName = "Stella", Address = "583-6561 Natoque Street", PhoneNumber = "1-600-452-6819", Email = "fringilla@magnis.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Talon", Password = "1", FirstName = "Calvin", LastName = "Willa", Address = "144-6838 Ut Rd.", PhoneNumber = "1-434-741-4877", Email = "Aliquam.rutrum@nunc.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Hall", Password = "1", FirstName = "George", LastName = "Nathan", Address = "1364 Cras Rd.", PhoneNumber = "1-157-856-9076", Email = "egestas@pedeSuspendisse.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Ray", Password = "1", FirstName = "Daryl", LastName = "Malcolm", Address = "Ap #449-9383 Non, Ave", PhoneNumber = "1-686-903-0704", Email = "ut@nullavulputate.ca", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Rudyard", Password = "1", FirstName = "Zahir", LastName = "Robin", Address = "672-6851 Donec St.", PhoneNumber = "1-644-791-6723", Email = "Praesent.eu@ornaresagittisfelis.co.uk", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Tiger", Password = "1", FirstName = "Calista", LastName = "Leah", Address = "P.O. Box 253, 5964 Vel Ave", PhoneNumber = "1-110-699-5276", Email = "neque.tellus@mollisneccursus.org", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Magee", Password = "1", FirstName = "Craig", LastName = "Eaton", Address = "3430 Scelerisque St.", PhoneNumber = "1-385-136-9709", Email = "libero@justoeuarcu.ca", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Dante", Password = "1", FirstName = "Blaine", LastName = "Hashim", Address = "P.O. Box 461, 5988 Libero. Rd.", PhoneNumber = "1-683-383-4824", Email = "auctor@afelis.ca", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Charles", Password = "1", FirstName = "Suki", LastName = "Lamar", Address = "P.O. Box 628, 1514 Vulputate Avenue", PhoneNumber = "1-525-916-7179", Email = "vel.est@sed.co.uk", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Ivor", Password = "1", FirstName = "Chase", LastName = "Geraldine", Address = "Ap #713-9291 Cras Rd.", PhoneNumber = "1-481-999-2188", Email = "venenatis.a@Donec.org", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Allen", Password = "1", FirstName = "Jesse", LastName = "Pamela", Address = "P.O. Box 169, 5562 Mauris Av.", PhoneNumber = "1-811-526-5469", Email = "egestas.Sed@tristiquealiquet.org", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Clinton", Password = "1", FirstName = "Haley", LastName = "Alfreda", Address = "635-207 Fermentum Ave", PhoneNumber = "1-622-454-3489", Email = "ultrices.Vivamus.rhoncus@egetodio.ca", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Owen", Password = "1", FirstName = "David", LastName = "Hedwig", Address = "984-1937 Enim. Av.", PhoneNumber = "1-209-989-5306", Email = "ultrices.Duis.volutpat@Utsemper.ca", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Oleg", Password = "1", FirstName = "Abraham", LastName = "Ocean", Address = "P.O. Box 938, 215 Lacinia. Avenue", PhoneNumber = "1-534-863-3653", Email = "congue.turpis.In@imperdietnec.net", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Brendan", Password = "1", FirstName = "Herman", LastName = "Neville", Address = "4080 Mus. Rd.", PhoneNumber = "1-311-199-3396", Email = "laoreet.ipsum@enimdiamvel.net", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Chester", Password = "1", FirstName = "Rhoda", LastName = "Dean", Address = "Ap #422-1030 Congue St.", PhoneNumber = "1-338-533-1482", Email = "odio.Aliquam@auctorvelit.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Jesse", Password = "1", FirstName = "Kevyn", LastName = "Kenyon", Address = "4796 Libero. Rd.", PhoneNumber = "1-181-506-3331", Email = "mi.lacinia@lacuspede.com", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Bruce", Password = "1", FirstName = "TaShya", LastName = "Sybill", Address = "8262 Est, DateOfBirth =DateTime.Now , Road", PhoneNumber = "1-793-198-6008", Email = "magna.Praesent@infaucibus.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Jasper", Password = "1", FirstName = "Thane", LastName = "Constance", Address = "9679 Praesent St.", PhoneNumber = "1-183-349-6530", Email = "consequat.dolor@morbitristiquesenectus.com", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Tanner", Password = "1", FirstName = "Lillian", LastName = "Glenna", Address = "Ap #554-1602 Feugiat Street", PhoneNumber = "1-114-830-2698", Email = "dolor@inhendreritconsectetuer.ca", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Bruno", Password = "1", FirstName = "Uriel", LastName = "Portia", Address = "218-7292 Pellentesque Ave", PhoneNumber = "1-722-510-1881", Email = "congue@Praesent.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Valentine", Password = "1", FirstName = "Melissa", LastName = "Cameron", Address = "P.O. Box 274, 4118 Lacinia Rd.", PhoneNumber = "1-306-903-9096", Email = "lacinia.at@Morbisitamet.edu", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Ezekiel", Password = "1", FirstName = "Ainsley", LastName = "Kiara", Address = "Ap #855-2576 Lorem Ave", PhoneNumber = "1-834-525-7585", Email = "enim.commodo.hendrerit@posuerecubiliaCurae.org", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Xenos", Password = "1", FirstName = "Arthur", LastName = "Lani", Address = "P.O. Box 931, 672 Phasellus Av.", PhoneNumber = "1-175-166-0245", Email = "tellus.eu@mattis.net", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Plato", Password = "1", FirstName = "Jasper", LastName = "Price", Address = "Ap #586-6599 Euismod Ave", PhoneNumber = "1-366-143-5224", Email = "posuere.vulputate.lacus@egetvenenatis.net", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Arsenio", Password = "1", FirstName = "Daria", LastName = "Mollie", Address = "172-7954 Sed St.", PhoneNumber = "1-113-924-5310", Email = "eu.enim.Etiam@justo.org", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Moses", Password = "1", FirstName = "Reese", LastName = "Wade", Address = "954-9045 Taciti Av.", PhoneNumber = "1-697-973-7698", Email = "dictum@et.net", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Mark", Password = "1", FirstName = "Nolan", LastName = "Vernon", Address = "P.O. Box 560, 1952 Etiam Avenue", PhoneNumber = "1-172-608-4069", Email = "nunc@Nulla.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Carlos", Password = "1", FirstName = "Zenaida", LastName = "Elizabeth", Address = "729 Suspendisse St.", PhoneNumber = "1-561-301-3824", Email = "Sed@eget.ca", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Julian", Password = "1", FirstName = "Lunea", LastName = "Omar", Address = "1523 Nibh. Rd.", PhoneNumber = "1-242-183-1980", Email = "dolor.Fusce.feugiat@habitant.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Thaddeus", Password = "1", FirstName = "Scott", LastName = "Brooke", Address = "6533 Quis Rd.", PhoneNumber = "1-340-373-5829", Email = "lacus.Nulla.tincidunt@arcuVestibulum.ca", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Edward", Password = "1", FirstName = "Kirk", LastName = "Darrel", Address = "222-8898 Id St.", PhoneNumber = "1-983-555-7851", Email = "Cum@Mauris.co.uk", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Elijah", Password = "1", FirstName = "Matthew", LastName = "Harriet", Address = "9827 Ullamcorper. Av.", PhoneNumber = "1-685-176-6916", Email = "vitae.nibh@eu.co.uk", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Randall", Password = "1", FirstName = "Keiko", LastName = "Allegra", Address = "293-3853 Bibendum Ave", PhoneNumber = "1-237-344-0929", Email = "Class@Donecelementum.com", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "August", Password = "1", FirstName = "Timothy", LastName = "Nero", Address = "P.O. Box 656, 1569 Vitae St.", PhoneNumber = "1-901-286-7870", Email = "varius.ultrices@ascelerisque.net", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Howard", Password = "1", FirstName = "Claire", LastName = "Maris", Address = "982-5279 Metus. Av.", PhoneNumber = "1-786-627-5116", Email = "ornare@pede.edu", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Guy", Password = "1", FirstName = "Talon", LastName = "Zelenia", Address = "Ap #256-8091 Ipsum Ave", PhoneNumber = "1-742-445-3183", Email = "Morbi.sit.amet@Fuscedolorquam.com", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Dale", Password = "1", FirstName = "Joel", LastName = "Grace", Address = "245-6185 Ut, Avenue", PhoneNumber = "1-366-744-0089", Email = "Donec@fringilla.ca", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Robert", Password = "1", FirstName = "Flynn", LastName = "Brian", Address = "9139 Quisque Ave", PhoneNumber = "1-910-649-2277", Email = "libero.nec@tempor.ca", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Griffin", Password = "1", FirstName = "Dana", LastName = "Lenore", Address = "Ap #957-625 Ultrices Rd.", PhoneNumber = "1-957-774-5494", Email = "erat.vel.pede@egetlaoreet.org", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Devin", Password = "1", FirstName = "Eve", LastName = "Shay", Address = "P.O. Box 530, 385 Nunc St.", PhoneNumber = "1-513-406-7632", Email = "quis@duilectus.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Garrison", Password = "1", FirstName = "Macaulay", LastName = "Chelsea", Address = "Ap #412-9001 Mauris. Rd.", PhoneNumber = "1-802-100-9354", Email = "Integer.tincidunt.aliquam@Donec.co.uk", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Hector", Password = "1", FirstName = "Anika", LastName = "Kay", Address = "Ap #430-5085 Non Street", PhoneNumber = "1-499-884-0436", Email = "urna.Nullam@luctus.ca", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Carlos", Password = "1", FirstName = "Hamilton", LastName = "Carson", Address = "Ap #491-1477 Non Ave", PhoneNumber = "1-363-388-9708", Email = "vulputate.eu.odio@idmagnaet.ca", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Alan", Password = "1", FirstName = "Gage", LastName = "Lars", Address = "1590 Luctus Street", PhoneNumber = "1-340-732-9994", Email = "ipsum.dolor.sit@Nuncmauris.co.uk", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Reed", Password = "1", FirstName = "Lacota", LastName = "Dana", Address = "7162 Sit St.", PhoneNumber = "1-350-794-5218", Email = "cursus.diam@ametrisusDonec.ca", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Hector", Password = "1", FirstName = "Tyler", LastName = "Jamal", Address = "P.O. Box 316, 4812 In St.", PhoneNumber = "1-952-259-1228", Email = "Sed@Duissit.co.uk", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Driscoll", Password = "1", FirstName = "Ella", LastName = "Adrian", Address = "P.O. Box 185, 7459 Pellentesque Rd.", PhoneNumber = "1-211-626-3632", Email = "in.hendrerit.consectetuer@massaMauris.org", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Walter", Password = "1", FirstName = "Tamara", LastName = "Justine", Address = "Ap #833-6105 Ante Rd.", PhoneNumber = "1-686-469-3064", Email = "amet@Nulla.net", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Omar", Password = "1", FirstName = "Zelenia", LastName = "Victor", Address = "P.O. Box 677, 2399 Nunc Av.", PhoneNumber = "1-661-731-4147", Email = "bibendum.Donec.felis@ideratEtiam.org", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Nehru", Password = "1", FirstName = "Raven", LastName = "Malik", Address = "Ap #147-3772 Lectus Street", PhoneNumber = "1-705-523-4254", Email = "Etiam@ultricesiaculis.org", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Dustin", Password = "1", FirstName = "Mollie", LastName = "Quincy", Address = "8886 Etiam Street", PhoneNumber = "1-179-790-7996", Email = "vitae.odio@estNuncullamcorper.co.uk", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Armando", Password = "1", FirstName = "Derek", LastName = "Brynn", Address = "Ap #314-257 Cursus Rd.", PhoneNumber = "1-112-917-2141", Email = "libero.at.auctor@arcu.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Kennedy", Password = "1", FirstName = "Carter", LastName = "Skyler", Address = "P.O. Box 213, 5323 Cras Avenue", PhoneNumber = "1-521-104-9997", Email = "dolor.egestas@hendrerit.org", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Moses", Password = "1", FirstName = "Marvin", LastName = "Maxwell", Address = "339-9799 Risus. Street", PhoneNumber = "1-650-352-6667", Email = "penatibus@Aenean.edu", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Leroy", Password = "1", FirstName = "Zahir", LastName = "Hilel", Address = "411-9737 Donec Street", PhoneNumber = "1-944-901-0148", Email = "Nam.consequat.dolor@imperdietdictum.net", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Jamal", Password = "1", FirstName = "Fuller", LastName = "Rina", Address = "822-7580 Lacinia. St.", PhoneNumber = "1-292-321-5208", Email = "Sed@vulputate.org", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Peter", Password = "1", FirstName = "Kaden", LastName = "Isabelle", Address = "Ap #959-9088 Quisque Rd.", PhoneNumber = "1-787-591-8465", Email = "libero.Integer.in@aliquet.ca", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Colton", Password = "1", FirstName = "Micah", LastName = "Channing", Address = "9219 Sit Road", PhoneNumber = "1-648-535-0474", Email = "odio.Nam@euismodin.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Brett", Password = "1", FirstName = "Lance", LastName = "Caldwell", Address = "6435 Sit St.", PhoneNumber = "1-347-572-3788", Email = "Duis.at.lacus@egestashendreritneque.co.uk", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Chester", Password = "1", FirstName = "Dana", LastName = "Grace", Address = "621-1156 Ullamcorper St.", PhoneNumber = "1-205-610-9782", Email = "senectus.et.netus@justoProin.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Stone", Password = "1", FirstName = "Evan", LastName = "Carly", Address = "8640 Aptent Ave", PhoneNumber = "1-183-692-6495", Email = "fermentum.risus.at@orciquislectus.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Driscoll", Password = "1", FirstName = "Mariko", LastName = "Wesley", Address = "Ap #145-3339 In Rd.", PhoneNumber = "1-129-221-0950", Email = "nibh.lacinia.orci@eu.edu", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Mufutau", Password = "1", FirstName = "Elaine", LastName = "Uma", Address = "P.O. Box 751, 8493 Feugiat St.", PhoneNumber = "1-857-621-4170", Email = "Integer@magna.ca", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Macon", Password = "1", FirstName = "Oleg", LastName = "Hoyt", Address = "Ap #261-5576 Nec Rd.", PhoneNumber = "1-902-851-7052", Email = "ante@ametorciUt.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Isaac", Password = "1", FirstName = "Ulla", LastName = "Quintessa", Address = "728-6410 Congue Av.", PhoneNumber = "1-571-876-2784", Email = "mi@arcuAliquam.ca", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Yoshio", Password = "1", FirstName = "Gillian", LastName = "Demetrius", Address = "454-9644 Tempor Ave", PhoneNumber = "1-216-313-6539", Email = "ullamcorper.nisl.arcu@nibhvulputate.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Grant", Password = "1", FirstName = "Summer", LastName = "Dustin", Address = "6247 Fusce Av.", PhoneNumber = "1-477-932-2740", Email = "diam@commodo.net", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Colby", Password = "1", FirstName = "Jack", LastName = "Jesse", Address = "6658 Aenean St.", PhoneNumber = "1-497-346-9368", Email = "Curae@habitantmorbi.com", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Raja", Password = "1", FirstName = "Brenda", LastName = "Debra", Address = "9638 Urna St.", PhoneNumber = "1-390-299-4792", Email = "tortor.Nunc@ipsumSuspendisse.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Dolan", Password = "1", FirstName = "Emerson", LastName = "Latifah", Address = "1280 Scelerisque, Av.", PhoneNumber = "1-844-264-5459", Email = "vitae.dolor.Donec@dictumcursusNunc.ca", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Clayton", Password = "1", FirstName = "Shad", LastName = "Leroy", Address = "305-9076 Ligula Av.", PhoneNumber = "1-636-302-5508", Email = "vehicula@odioa.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Dante", Password = "1", FirstName = "Slade", LastName = "Maris", Address = "2037 Donec St.", PhoneNumber = "1-910-732-6277", Email = "tempor.erat@loremluctus.org", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Byron", Password = "1", FirstName = "Prescott", LastName = "Keefe", Address = "882-6298 Nulla St.", PhoneNumber = "1-776-582-0203", Email = "fringilla@temporlorem.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Porter", Password = "1", FirstName = "Igor", LastName = "Jamalia", Address = "2359 Sapien Road", PhoneNumber = "1-486-191-2026", Email = "Sed@ultriciesdignissim.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Elton", Password = "1", FirstName = "Lenore", LastName = "Danielle", Address = "P.O. Box 315, 2981 Est, DateOfBirth =DateTime.Now , Road", PhoneNumber = "1-295-893-0664", Email = "Proin.nisl.sem@ullamcorpervelitin.co.uk", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Francis", Password = "1", FirstName = "Brian", LastName = "Sebastian", Address = "P.O. Box 162, 6853 Vitae Street", PhoneNumber = "1-999-492-6273", Email = "aliquet.diam.Sed@volutpat.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Peter", Password = "1", FirstName = "Travis", LastName = "Kevyn", Address = "600-5061 Duis St.", PhoneNumber = "1-135-860-9018", Email = "risus.varius@pellentesqueafacilisis.ca", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Wesley", Password = "1", FirstName = "Roary", LastName = "Jamalia", Address = "4167 Et Street", PhoneNumber = "1-374-527-2583", Email = "eu.augue.porttitor@nasceturridiculusmus.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Oleg", Password = "1", FirstName = "Amal", LastName = "Quentin", Address = "Ap #981-3860 Sed St.", PhoneNumber = "1-341-817-4569", Email = "erat@vitaeeratvel.co.uk", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Jason", Password = "1", FirstName = "Brandon", LastName = "Rinah", Address = "572-337 Euismod Street", PhoneNumber = "1-502-425-0256", Email = "ornare@mauris.com", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Bevis", Password = "1", FirstName = "Charlotte", LastName = "Stephanie", Address = "P.O. Box 836, 484 Eget Street", PhoneNumber = "1-246-132-7908", Email = "ut@gravida.co.uk", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Quinlan", Password = "1", FirstName = "Amir", LastName = "Moses", Address = "2662 Dignissim Ave", PhoneNumber = "1-689-186-7857", Email = "Cras@sitamet.co.uk", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Keane", Password = "1", FirstName = "Athena", LastName = "Latifah", Address = "4706 Dictum Ave", PhoneNumber = "1-825-912-0382", Email = "cubilia@sociis.ca", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Reuben", Password = "1", FirstName = "Burke", LastName = "Nora", Address = "958-3865 Orci Avenue", PhoneNumber = "1-280-952-7707", Email = "a.felis.ullamcorper@fringillapurus.co.uk", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Ezra", Password = "1", FirstName = "Alvin", LastName = "Janna", Address = "748-9311 Integer Rd.", PhoneNumber = "1-449-287-3632", Email = "dolor.sit.amet@nuncrisus.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Daquan", Password = "1", FirstName = "Jane", LastName = "Baker", Address = "Ap #191-2571 Fames Ave", PhoneNumber = "1-449-731-4071", Email = "ante@ut.net", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Ignatius", Password = "1", FirstName = "Fritz", LastName = "Ursula", Address = "P.O. Box 958, 2992 Lacus. Rd.", PhoneNumber = "1-677-962-3134", Email = "mauris@Aeneangravidanunc.co.uk", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Daniel", Password = "1", FirstName = "Ayanna", LastName = "Burton", Address = "808-9917 Leo St.", PhoneNumber = "1-580-798-0622", Email = "pellentesque@lobortisnisi.net", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Octavius", Password = "1", FirstName = "Yetta", LastName = "Montana", Address = "Ap #461-5065 Sed Ave", PhoneNumber = "1-965-620-8343", Email = "magna.Suspendisse.tristique@Integervitae.co.uk", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Charles", Password = "1", FirstName = "Alyssa", LastName = "Kennedy", Address = "P.O. Box 634, 4066 Eget Av.", PhoneNumber = "1-496-477-7419", Email = "Etiam@eratnonummyultricies.com", DateOfBirth =DateTime.Now , RoleId = 3 },
                    new User { Username = "Buckminster", Password = "1", FirstName = "Rogan", LastName = "Burke", Address = "Ap #417-5648 Nisi Street", PhoneNumber = "1-638-510-2140", Email = "quis.massa@nuncinterdumfeugiat.com", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Wallace", Password = "1", FirstName = "Paloma", LastName = "Rooney", Address = "1273 At Avenue", PhoneNumber = "1-657-318-0079", Email = "ridiculus.mus@aliquam.edu", DateOfBirth =DateTime.Now , RoleId = 1 },
                    new User { Username = "Wayne", Password = "1", FirstName = "Ainsley", LastName = "Anjolie", Address = "498-2842 Tincidunt. Rd.", PhoneNumber = "1-186-592-1769", Email = "Aliquam@Proinsedturpis.com", DateOfBirth =DateTime.Now , RoleId = 2 },
                    new User { Username = "Yuli", Password = "1", FirstName = "Desiree", LastName = "Cadman", Address = "P.O. Box 536, 1923 Sagittis Rd.", PhoneNumber = "1-943-285-3137", Email = "blandit.Nam@ultriciessem.org", DateOfBirth =DateTime.Now , RoleId = 3 }
                };
            foreach (var item in users)
            {
                context.Users.Add(item);
            }
            context.SaveChanges();

            var products = new List<Product> {
                new Product { CategoryId = 4, Price = 234, Desciption = "Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra," },
                new Product { CategoryId = 2, Price = 186, Desciption = "risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere" },
                new Product { CategoryId = 5, Price = 69, Desciption = "lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing." },
                new Product { CategoryId = 2, Price = 453, Desciption = "ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla" },
                new Product { CategoryId = 2, Price = 1144, Desciption = "ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non" },
                new Product { CategoryId = 2, Price = 751, Desciption = "diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum" },
                new Product { CategoryId = 5, Price = 324, Desciption = "orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor" },
                new Product { CategoryId = 3, Price = 851, Desciption = "adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla" },
                new Product { CategoryId = 5, Price = 542, Desciption = "ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium" },
                new Product { CategoryId = 2, Price = 431, Desciption = "nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus." },
                new Product { CategoryId = 1, Price = 750, Desciption = "semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem" },
                new Product { CategoryId = 4, Price = 28, Desciption = "mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu." },
                new Product { CategoryId = 1, Price = 653, Desciption = "facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer" },
                new Product { CategoryId = 5, Price = 758, Desciption = "egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt" },
                new Product { CategoryId = 5, Price = 161, Desciption = "Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed" },
                new Product { CategoryId = 3, Price = 612, Desciption = "purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna" },
                new Product { CategoryId = 5, Price = 1003, Desciption = "nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor" },
                new Product { CategoryId = 4, Price = 403, Desciption = "lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce" },
                new Product { CategoryId = 1, Price = 379, Desciption = "rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti" },
                new Product { CategoryId = 5, Price = 153, Desciption = "Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui," },
                new Product { CategoryId = 5, Price = 1197, Desciption = "odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum" },
                new Product { CategoryId = 4, Price = 183, Desciption = "erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus" },
                new Product { CategoryId = 2, Price = 883, Desciption = "scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum" },
                new Product { CategoryId = 5, Price = 628, Desciption = "tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa." },
                new Product { CategoryId = 1, Price = 992, Desciption = "Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit" },
                new Product { CategoryId = 4, Price = 498, Desciption = "egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet" },
                new Product { CategoryId = 5, Price = 780, Desciption = "Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec" },
                new Product { CategoryId = 2, Price = 1002, Desciption = "ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur" },
                new Product { CategoryId = 2, Price = 690, Desciption = "et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur" },
                new Product { CategoryId = 4, Price = 1111, Desciption = "Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus" },
                new Product { CategoryId = 4, Price = 95, Desciption = "eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis" },
                new Product { CategoryId = 4, Price = 92, Desciption = "facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non" },
                new Product { CategoryId = 2, Price = 259, Desciption = "cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget" },
                new Product { CategoryId = 1, Price = 1071, Desciption = "molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum" },
                new Product { CategoryId = 3, Price = 1107, Desciption = "ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit." },
                new Product { CategoryId = 1, Price = 324, Desciption = "sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras" },
                new Product { CategoryId = 2, Price = 391, Desciption = "arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus" },
                new Product { CategoryId = 4, Price = 448, Desciption = "eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel" },
                new Product { CategoryId = 4, Price = 869, Desciption = "montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam" },
                new Product { CategoryId = 2, Price = 199, Desciption = "urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus." },
                new Product { CategoryId = 2, Price = 1119, Desciption = "odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut" },
                new Product { CategoryId = 1, Price = 316, Desciption = "et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet." },
                new Product { CategoryId = 1, Price = 121, Desciption = "malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat" },
                new Product { CategoryId = 1, Price = 855, Desciption = "eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla" },
                new Product { CategoryId = 2, Price = 780, Desciption = "eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla." },
                new Product { CategoryId = 3, Price = 325, Desciption = "nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non," },
                new Product { CategoryId = 4, Price = 895, Desciption = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy" },
                new Product { CategoryId = 2, Price = 172, Desciption = "diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus." },
                new Product { CategoryId = 5, Price = 189, Desciption = "Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero" },
                new Product { CategoryId = 4, Price = 1188, Desciption = "nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae" },
                new Product { CategoryId = 2, Price = 1194, Desciption = "Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan" },
                new Product { CategoryId = 1, Price = 333, Desciption = "et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt" },
                new Product { CategoryId = 5, Price = 142, Desciption = "libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo" },
                new Product { CategoryId = 1, Price = 963, Desciption = "gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis" },
                new Product { CategoryId = 2, Price = 221, Desciption = "Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui" },
                new Product { CategoryId = 1, Price = 284, Desciption = "nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor" },
                new Product { CategoryId = 2, Price = 481, Desciption = "non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in," },
                new Product { CategoryId = 3, Price = 631, Desciption = "nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit" },
                new Product { CategoryId = 3, Price = 1061, Desciption = "lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula" },
                new Product { CategoryId = 4, Price = 1181, Desciption = "iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim" },
                new Product { CategoryId = 3, Price = 894, Desciption = "at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean" },
                new Product { CategoryId = 3, Price = 698, Desciption = "scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis" },
                new Product { CategoryId = 1, Price = 859, Desciption = "ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in" },
                new Product { CategoryId = 2, Price = 274, Desciption = "pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem." },
                new Product { CategoryId = 2, Price = 148, Desciption = "sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et" },
                new Product { CategoryId = 1, Price = 193, Desciption = "et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis" },
                new Product { CategoryId = 3, Price = 952, Desciption = "non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin" },
                new Product { CategoryId = 2, Price = 958, Desciption = "Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim," },
                new Product { CategoryId = 3, Price = 455, Desciption = "in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus." },
                new Product { CategoryId = 1, Price = 518, Desciption = "velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac," },
                new Product { CategoryId = 1, Price = 479, Desciption = "erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu," },
                new Product { CategoryId = 3, Price = 560, Desciption = "aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu." },
                new Product { CategoryId = 2, Price = 948, Desciption = "quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus," },
                new Product { CategoryId = 5, Price = 250, Desciption = "orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula." },
                new Product { CategoryId = 3, Price = 779, Desciption = "tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa" },
                new Product { CategoryId = 1, Price = 296, Desciption = "commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque" },
                new Product { CategoryId = 4, Price = 653, Desciption = "dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis" },
                new Product { CategoryId = 4, Price = 435, Desciption = "et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor" },
                new Product { CategoryId = 3, Price = 1092, Desciption = "Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor." },
                new Product { CategoryId = 3, Price = 228, Desciption = "ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi" },
                new Product { CategoryId = 4, Price = 861, Desciption = "ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices" },
                new Product { CategoryId = 5, Price = 24, Desciption = "arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan interdum libero" },
                new Product { CategoryId = 2, Price = 295, Desciption = "a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies" },
                new Product { CategoryId = 2, Price = 718, Desciption = "blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum" },
                new Product { CategoryId = 3, Price = 637, Desciption = "a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget" },
                new Product { CategoryId = 2, Price = 974, Desciption = "sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla." },
                new Product { CategoryId = 2, Price = 1175, Desciption = "mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper." },
                new Product { CategoryId = 3, Price = 378, Desciption = "parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo" },
                new Product { CategoryId = 4, Price = 1048, Desciption = "sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis" },
                new Product { CategoryId = 1, Price = 757, Desciption = "montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc" },
                new Product { CategoryId = 3, Price = 643, Desciption = "lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero." },
                new Product { CategoryId = 1, Price = 1031, Desciption = "torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie" },
                new Product { CategoryId = 3, Price = 281, Desciption = "velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit" },
                new Product { CategoryId = 3, Price = 475, Desciption = "a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus" },
                new Product { CategoryId = 5, Price = 334, Desciption = "aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor" },
                new Product { CategoryId = 3, Price = 857, Desciption = "erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus" },
                new Product { CategoryId = 3, Price = 406, Desciption = "Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem" },
                new Product { CategoryId = 4, Price = 1179, Desciption = "urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum" },
                new Product { CategoryId = 1, Price = 22, Desciption = "aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in" },
                new Product { CategoryId = 4, Price = 161, Desciption = "primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus" }
            };

            foreach (var item in products)
            {
                context.Products.Add(item);
            }
            context.SaveChanges();


        }
    }
}
